- name: fetch the current Go version
  shell: curl --silent https://go.dev/VERSION?m=text | head -n 1
  register: go_latest
  tags:
    - lang
    - go

- name: download installer
  get_url:
    url: https://go.dev/dl/{{ go_latest.stdout }}.linux-amd64.tar.gz
    dest: /tmp/{{ go_latest.stdout }}.linux-amd64.tar.gz
    mode: '0755'
    force: 'yes'
  tags:
    - lang
    - go

- name: install go
  shell:  rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/{{ go_latest.stdout }}.linux-amd64.tar.gz
  tags:
    - lang
    - go

- name: ensure go binary path is in ~/.zshrc
  become_user: solo
  lineinfile:
    path: ~/.zshrc
    line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
    regexp: '^export PATH=.*:/usr/local/go/bin:.*$'
    create: true
    state: present
  tags:
    - lang
    - go
