- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: download installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
    - lang

- name: install rust/cargo
  become_user: solo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
    - lang

- name: source cargo env 
  become_user: solo
  when: cargo_exists is failed
  shell: . $HOME/.cargo/env
  tags:
    - rust
    - lang
