- name: install zsh
  apt: name=zsh
  tags: 
  - zsh

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become_user: solo
  tags: 
  - zsh

- name: install zsh theme
  become_user: solo
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    depth: 1
    dest: "/home/solo/.oh-my-zsh/themes/powerlevel10k"

- name: install zsh autosuggestions
  become_user: solo
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "/home/solo/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: 
  - zsh

- name: change default shell
  ansible.builtin.user:
    name: solo
    shell: /bin/zsh
